# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{webrat-scraper}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["JT Zemp"]
  s.date = %q{2009-10-10}
  s.description = %q{A web scraper using Webrat & Mechanize}
  s.email = %q{jtzemp@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/webrat_scraper.rb",
     "spec/fakeweb_fixtures/fake_form.html",
     "spec/fakeweb_fixtures/fake_form_action.html",
     "spec/spec_helper.rb",
     "spec/webrat_scraper_spec.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/jtzemp/webrat-scraper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{A web scraper using Webrat & Mechanize - does acceptance-based web scraping relying on the great webrat behavior description language.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/webrat_scraper_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mechanize>, [">= 0.9.3"])
      s.add_runtime_dependency(%q<webrat>, ["= 0.4.5"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
    else
      s.add_dependency(%q<mechanize>, [">= 0.9.3"])
      s.add_dependency(%q<webrat>, ["= 0.4.5"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
    end
  else
    s.add_dependency(%q<mechanize>, [">= 0.9.3"])
    s.add_dependency(%q<webrat>, ["= 0.4.5"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
  end
end
